# Generated by Django 5.1.5 on 2025-02-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(default='profiles/user/default.jpg', upload_to='static/staticfiles/images/profiles/user'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_proof',
            field=models.FileField(upload_to='static/staticfiles/images/profiles/proof'),
        ),
    ]
