# Generated by Django 5.1.5 on 2025-02-28 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0003_alter_tbl_user_user_photo_alter_tbl_user_user_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(default='user-default.png', upload_to='User'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_proof',
            field=models.FileField(upload_to='User/proof'),
        ),
    ]
