# Generated by Django 5.1.5 on 2025-03-02 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0005_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(default='user-default.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='tbl_user',
            name='user_proof',
            field=models.FileField(upload_to='profile/proof/'),
        ),
    ]
