# Generated by Django 5.1.5 on 2025-03-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0006_alter_tbl_user_user_photo_alter_tbl_user_user_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_user',
            name='user_photo',
            field=models.FileField(default='media/user-default.png', upload_to='profile/'),
        ),
    ]
