# Generated by Django 5.1.5 on 2025-03-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0010_alter_tbl_user_user_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_user',
            name='user_latitude',
            field=models.CharField(default=(9.942767, 76.64212), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_longitude',
            field=models.CharField(default=(9.942767, 76.64212), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_user',
            name='user_status',
            field=models.IntegerField(default=0),
        ),
    ]
