# Generated by Django 5.1.5 on 2025-03-11 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0011_tbl_user_user_latitude_tbl_user_user_longitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_user',
            name='user_location',
        ),
    ]
