# Generated by Django 5.1.5 on 2025-03-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_alter_tbl_gallery_gallery_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tool',
            name='gallery_file',
            field=models.FileField(default='Assets/default.jpg', upload_to='Assets/gallery'),
        ),
        migrations.DeleteModel(
            name='tbl_gallery',
        ),
    ]
