# Generated by Django 5.1.5 on 2025-03-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdm', '0009_delete_tbl_district_delete_tbl_tags'),
        ('User', '0016_tbl_tool_gallery_file_delete_tbl_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_renttool',
            name='rent_tool_qty',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tbl_tool',
            name='category',
            field=models.ForeignKey(default=978, on_delete=django.db.models.deletion.CASCADE, to='SiteAdm.tbl_category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_tool',
            name='qty',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='tbl_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_image', models.FileField(default='Assets/default.jpg', upload_to='Assets/gallery')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_tool')),
            ],
        ),
    ]
