# Generated by Django 5.1.5 on 2025-03-11 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdm', '0009_delete_tbl_district_delete_tbl_tags'),
        ('User', '0017_tbl_renttool_rent_tool_qty_tbl_tool_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_tool',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SiteAdm.tbl_category'),
        ),
    ]
