# Generated by Django 5.1.5 on 2025-03-11 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0018_alter_tbl_tool_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_tool',
            name='category',
        ),
    ]
