# Generated by Django 5.1.5 on 2025-03-21 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SiteAdm', '0009_delete_tbl_district_delete_tbl_tags'),
        ('Guest', '0013_alter_tbl_user_user_latitude_and_more'),
        ('User', '0019_remove_tbl_tool_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tool',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='SiteAdm.tbl_category'),
        ),
        migrations.CreateModel(
            name='tbl_payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_amount', models.CharField(max_length=50)),
                ('payment_date', models.DateField(null=True)),
                ('payment_status', models.IntegerField(default=0)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.tbl_renttool')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
