# Generated by Django 5.1.5 on 2025-03-31 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0020_tbl_tool_category_tbl_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_tool',
            name='tool_deposit',
            field=models.CharField(default=100, max_length=50),
            preserve_default=False,
        ),
    ]
