# Generated by Django 5.1.5 on 2025-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0021_tbl_tool_tool_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_renttool',
            name='cancel_fee',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tbl_renttool',
            name='late_fee',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
